[global-vars]
arr_base_dirs=( "pool" "dists" )
apt_template_list_fullpath_filename="/usr/share/berb-apt-mgr/apt_template.list"

templ_dir="/usr/share/berb-apt-mgr"
apt_conf_dir="apt-ftp-configs"
aptftp_conf_file="aptftp.conf"
aptftp_conf_relpath_file="${apt_conf_dir}/aptftp.conf"
aptgen_conf_file="aptgenerate.conf"
aptgen_conf_relpath_file="${apt_conf_dir}/aptgenerate.conf"

aptftp_templ_file="${templ_dir}/aptftp_conf_template.conf"
aptgen_templ_file="${templ_dir}/aptgenerate_template.conf"
aptconf_BinDir_templ_file="${templ_dir}/aptconf_BinDir_template.conf"
aptconf_SrcDir_templ_file="${templ_dir}/aptconf_SrcDir_template.conf"
aptconf_Tree_templ_file="${templ_dir}/aptconf_Tree_template.conf"

arr_aptconf_templates=( "${aptftp_templ_file}" "${aptgen_templ_file}" "${aptconf_BinDir_templ_file}" "${aptconf_SrcDir_templ_file}" "${aptconf_tree_templ_file}" )
