arr_base_dirs=( "pool" "dists" )

aptftp_Default_templ_fullpath_filename="/usr/share/berb-apt-mgr/aptftp_Default_template.conf"
aptftp_Release_templ_fullpath_filename="/usr/share/berb-apt-mgr/aptftp_Release_template.conf"
aptftp_Directorys_templ_fullpath_filename="/usr/share/berb-apt-mgr/aptftp_Directorys_template.conf"
aptftp_conf_filename="aptftp.conf"
aptgenerate_conf_filename="aptgenerate.conf"
arr_aptconf_templates=( "${aptftp_Default_templ_fullpath_filename}" "${aptftp_Release_templ_fullpath_filename}" "${aptftp_Directorys_templ_fullpath_filename}" )
apt_ftp_config_dirname="apt-ftp-configs"
