BinDirectory "dists/REPLACE_RELEASE/main/binary-REPLACE_ARCH" {
  Packages "dists/REPLACE_RELEASE/main/binary-REPLACE_ARCH/Packages";
  Contents "dists/REPLACE_RELEASE/Contents-REPLACE_ARCH";
  BinCacheDB "packages-REPLACE_RELEASE-arch-specific.db";
};

SrcDirectory "dists/REPLACE_RELEASE/main/source" {
  Sources "dists/REPLACE_RELEASE/main/source/Sources";
  SrcCacheDB "sources-REPLACE_RELEASE.db";
};

