Default {
   Packages::Extensions ".deb";
   Packages::Compress ". gzip bzip2";
   Sources::Compress ". gzip bzip2";
   Contents::Compress "gzip bzip2";
};

Dir {
  ArchiveDir "./pool";
  CacheDir "./cache";
  StateDir "./state";
};

TreeDefault {
  BinCacheDB "packages-arch-specific.db";
  SrcCacheDB "sources.db";
}

