BinDirectory "dists/RELEASE/main/binary-ARCH" {
  Packages "dists/RELEASE/main/binary-ARCH/Packages";
  Contents "dists/RELEASE/Contents-ARCH";
};

Tree "dists/RELEASE" {
  Sections "main";
  Architectures ARCHS";
};
