APT::FTPArchive::Release {
  Origin "REPLACE_ORIGIN";
  Label "REPLACE_LABEL";
  Suite "REPLACE_RELEASE";
  Codename "REPLACE_RELEASE";
  Architectures replace_archs_list;
  Components "main";
  Description "REPLACE_DESCRIPTION for release REPLACE_RELEASE and arch REPLACE_ARCH";
};

BinDirectory "dists/REPLACE_RELEASE/main/binary-REPLACE_ARCH" {
  Packages "dists/REPLACE_RELEASE/main/binary-REPLACE_ARCH/Packages";
  Contents "dists/REPLACE_RELEASE/Contents-REPLACE_ARCH";
};

Tree "dists/REPLACE_RELEASE" {
  Sections "main";
  Architectures replace_archs_list;
};
