## Next will be used to name the gpg and apt list files
gpg_pub_filename="some_file_name_without_ext"

releases_origin="some_origin"
releases_label="some_label"
releases_description="some_description" 

arr_releases=( "stable" "testing" )
arr_archs=( "all" "arm64" "amd64" "i386" )
arr_base_dirs=( "pool" "dists" )

aptftp_conf_templ="/usr/share/berb-apt-mgr/aptftp_template.conf"
aptgenerate_conf_templ="/usr/share/berb-apt-mgr/aptgenerate_template.conf"
#arr_aptconf_templates=( "${aptftp_conf_templ}" "${aptgenerate_conf_templ}" )
apt_ftp_config_dirname="apt-ftp-configs"
